### PR TITLE
Added Kleine speler post-fix title for Xander Voorvaart

### PR DESCRIPTION
**Pull request by pde-bakk**
Everybody knows Xander loves calling people a 'Kleine speler'.
The best way to get back at him, is obviously to give him a little taste of his own medicine!

### CODE REVIEW

**Comment by pde-bakk** [comment]
@FreekBes please

**Comment by pde-bakk** [comment]
image

This is what it looks like.

**Comment by saladuit** [comment]
terecht

**Comment by saladuit** [comment]
Dit zijn de nu echt de belangrijke updates

**Comment by FreekBes** [comment]
While I appreciate the joke, I don't want this extension to be used as a way to add custom titles to users, circumventing Intra. Thus, I am not merging this. Sorry!

**Comment by pde-bakk** [comment]
next year as an easter egg then

**Pull request closed without merging**
